/*
 * To see the assembly code generated by the C compiler, can use -S 
 * on the command line:
 *
 * gcc -Og -S mstore.c
 *
 * which will cause GCC to run the compiler, generating the assembly
 * file mstore.s, and go no further
 *
 * If you use:
 *
 * gcc -Og -c mstore.c
 *
 * -c will cause GCC to both compile and assemble the code. This
 *  generates an object-code file mstore.o, which is in binary 
 *  format
 *
 *  from there, can use objdump (Linux command-line program for displaying
 *  various information about object files) with the -d flag to act as a 
 *  disassembler
*/

long mult2(long, long);

void multstore(long x, long y, long *dest) {
	long t = mult2(x, y);
	*dest = t;
}
